basePath: /
definitions:
  models.Image:
    properties:
      id:
        type: string
      image_url:
        type: string
      position:
        type: integer
      user:
        $ref: '#/definitions/models.User'
      username:
        type: string
    type: object
  models.User:
    properties:
      company_name:
        type: string
      description:
        type: string
      location:
        type: string
      name:
        type: string
      password:
        type: string
      professional_title:
        type: string
      username:
        type: string
    type: object
  models.UserPublic:
    properties:
      company_name:
        type: string
      description:
        type: string
      image:
        items:
          $ref: '#/definitions/models.Image'
        type: array
      location:
        type: string
      name:
        type: string
      professional_title:
        type: string
      username:
        type: string
    type: object
  requests.ProfileRequest:
    properties:
      company_name:
        type: string
      description:
        type: string
      location:
        type: string
      name:
        type: string
      professional_title:
        type: string
    type: object
  requests.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:5995
info:
  contact:
    email: support@linkmatch.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API documentation for the LinkMatch application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: LinkMatch API
  version: "1.0"
paths:
  /api/profile:
    get:
      consumes:
      - application/json
      description: Returns a JSON with the user that requested it
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Get Profile
      tags:
      - Profile
    put:
      consumes:
      - application/json
      description: Updates the profile with the given body
      parameters:
      - description: Profile body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.ProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserPublic'
      security:
      - Bearer: []
      summary: Update Profile
      tags:
      - Profile
  /api/profile/parse-cv:
    post:
      consumes:
      - multipart/form-data
      description: Returns a JSON with the parsed CV
      parameters:
      - description: CV file
        in: formData
        name: cv
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Parse CV
      tags:
      - Profile
  /auth/login:
    post:
      consumes:
      - application/json
      description: Handles user login
      parameters:
      - description: Login body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.RegisterRequest'
      produces:
      - application/json
      responses: {}
      summary: Login a user
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Handles user registration
      parameters:
      - description: Register body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.RegisterRequest'
      produces:
      - application/json
      responses: {}
      summary: Register a new user
      tags:
      - Auth
schemes:
- http
securityDefinitions:
  Bearer:
    description: Enter your bearer token in the format **Bearer &lt;token>**
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
